#print(sorted(set(dir(int)) - set(dir(object))))

print("~" * 77)
print("+", [i + j for i in range(-3, 4) for j in range(-3, 4)])
print("-", [i - j for i in range(-3, 4) for j in range(-3, 4)])
print("\n*", [i * j for i in range(-3, 4) for j in range(-3, 4)])
print("/", [i / j if j != 0 else "?" for i in range(-3, 4) for j in range(-3, 4)])
print("\n%", [i % j if j != 0 else "?" for i in range(-3, 4) for j in range(-3, 4)])
print("//", [i // j if j != 0 else "?" for i in range(-3, 4) for j in range(-3, 4)])
print("divmod", [divmod(i, j) if j != 0 else "?" for i in range(-3, 4) for j in range(-3, 4)])
print("\n**", ["?" if i == 0 and j < 0 else i ** j for i in range(-3, 4) for j in range(-3, 4)])
print("\n|", [i | j for i in range(-3, 4) for j in range(-3, 4)])
print("&", [i & j for i in range(-3, 4) for j in range(-3, 4)])
print("^", [i ^ j for i in range(-3, 4) for j in range(-3, 4)])
print("\nunar +", [+i for i in range(-33, 34)])
print("unar -", [-i for i in range(-33, 34)])
print("unar ~", [~i for i in range(-33, 34)])
print("\n<<", [i << j for i in range(-3, 4) for j in range(8)])
print(">>", [i >> j for i in range(-3, 4) for j in range(8)])

print("\n" + "~" * 77)
print("\n==", ''.join("+" if i == j else "-" for i in range(-3, 4) for j in range(-3, 4)))
print("!=", ''.join("+" if i != j else "-" for i in range(-3, 4) for j in range(-3, 4)))
print("< ", ''.join("+" if i < j else "-" for i in range(-3, 4) for j in range(-3, 4)))
print(">=", ''.join("+" if i >= j else "-" for i in range(-3, 4) for j in range(-3, 4)))
print("> ", ''.join("+" if i > j else "-" for i in range(-3, 4) for j in range(-3, 4)))
print("<=", ''.join("+" if i <= j else "-" for i in range(-3, 4) for j in range(-3, 4)))

print("\n" + "~" * 77)
print("bit_length:", [i.bit_length() for i in range(-33, 34)])
print("\nconjugate:", [i.conjugate() for i in range(-33, 34)])
print("\nnumerator:", [i.numerator for i in range(-33, 34)])
print("denominator:", [i.denominator for i in range(-33, 34)])
print("\nreal:", [i.real for i in range(-33, 34)])
print("imag:", [i.imag for i in range(-33, 34)])
nums = ((0, 0), (255, 255), (128, 127), (127, 128), (64, 32), (32, 64), (150, 30), (30, 150), (150, 200), (200, 150), (0,), (1,), (255,), (254,), (128,), (127,), (0, 0, 0), (0, 5, 6), (6, 5, 0))
print("\nfrom_bytes (BE):", [int.from_bytes(bytes(num), "big") for num in nums])
print("from_bytes (LE):", [int.from_bytes(bytes(num), "little") for num in nums])
arr = [2 ** i + d for i in range(1, 20) for d in range(-1, 2)]
print("\nto_bytes (BE):", [tuple(i.to_bytes(1 if i < 256 else 2 if i < 256**2 else 3, "big")) for i in arr])
print("to_bytes (LE):", [tuple(i.to_bytes(1 if i < 256 else 2 if i < 256**2 else 3, "little")) for i in arr])

print("\n" + "~" * 77)
print("abs:", [abs(i) for i in range(-33, 34)])
print("bool:", ''.join("+" if bool(i) else "-" for i in range(-33, 34)))
print("ceil:", [i.__ceil__() for i in range(-33, 34)])
print("float:", [i.__float__() for i in range(-33, 34)])
print("floor:", [i.__floor__() for i in range(-33, 34)])
print("hash:", [hash(2 ** i + 5) for i in range(65)])
print("index:", [i.__index__() for i in range(-33, 34)])
print("repr:", [repr(i) for i in range(-33, 34)])
print("round:", [round(i) for i in range(-33, 34)])
print("str:", [str(i) for i in range(-33, 34)])
print("trunc:", [i.__trunc__() for i in range(-33, 34)])
